name: Version bumps

on:
  schedule:
    - cron:  '17 1,7,13,19 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  online-version-bump:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write' # for OIDC auth for GCP authentication
      contents: 'write' # for committing to main

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d
        with:
          token_format: access_token
          workload_identity_provider: YOUR_IDENTITY_PROVIDER_HERE
          service_account: YOUR_SERVICE_ACCOUNT_HERE

      - name: Bump online versions
        uses: jku/repository-playground/playground/actions/online-version-bump@main

  offline-version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write' # for committing to signing event branch
      actions: 'write' # for dispatching signing event workflow

    steps:
      - name: Create signing events for offline version bumps
        uses: jku/repository-playground/playground/actions/offline-version-bump@main
